const s = {
  card: {
    background: '#fff',
    border: '0.5px solid #e5e5e3',
    borderRadius: 12,
    padding: '1.25rem',
  },
  input: {
    display: 'block',
    width: '100%',
    fontSize: 13,
    padding: '8px 10px',
    borderRadius: 8,
    border: '0.5px solid #d5d5d3',
    background: '#fff',
    color: '#111',
    marginBottom: 12,
    outline: 'none',
    fontFamily: 'inherit',
  },
  select: {
    display: 'block',
    width: '100%',
    fontSize: 13,
    padding: '8px 10px',
    borderRadius: 8,
    border: '0.5px solid #d5d5d3',
    background: '#fff',
    color: '#111',
    marginBottom: 12,
    outline: 'none',
    fontFamily: 'inherit',
  },
  label: {
    display: 'block',
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
    fontWeight: 500,
  },
  btnPrimary: {
    background: '#CC1818',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 18px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnSecondary: {
    background: '#fff',
    color: '#333',
    border: '0.5px solid #d5d5d3',
    borderRadius: 8,
    padding: '7px 14px',
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
};

export default s;
